[[SCS_GPU]]
arch = "x86_64"
git-tree-sha1 = "8ae303d28090f987e71f6f5337ab4cf2d8a458bd"
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "0ce132a1806f6b5909e3aebb880a8c58ca90531c8858ff6ee3c2b43f449d9c61"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v2.1.4+0/SCS_GPU.v2.1.4.x86_64-linux-gnu.tar.gz"
