[[SCS_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "8686f8b84aba9fe32eb1e90a602fff1b016cf0dc"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "e51e7c32151d22551fabcf7c656f1e9b374deb8d6f2e04aeca6027afa6dfc89d"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "6b833c36f972875032d896f6a774060ae1e85560"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "1ee9237d026af047a92a16fd19bc22e80daf3524f9ca88dac534ebcc6dc3e15f"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "f2a291d1a2ba3a52f822b3002fd454c0f99946e6"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "bfc9fc683a3e89d63164e44882059d7324f6987a1b1705d5da95432254a4ffcd"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "3a86d004a2ff0c0c6dadb46c2d800e801b19c940"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "4ddd08b2d04c56636e495e31c98ae1ca4b4dcabb8d2ea87f30c22b18b2aa32c0"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "4fc4a418e421d17da9aabb3b39e17dafcc2f513c"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "016c06f06779a6443c67065c69949900b0c1d65d955e9a861cd08e402a2f7a3d"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "62f45b811e8bc44788baf91d29d0e1079eaf9a40"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "672857c781101510618bbf2ffa3f537670d50f3d90963ed3ee16ae404758eb91"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "f178088ac5e8a82d59b8271dbfc2cdd6a94cd97e"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "43b5866d4a6764ef61775afcfc1b59c60f69d0f605c4691d42bd8d7cc3075c2a"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "70f0af25c2f1f6fa6626092ea74b3be9d2da71f6"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "8d39f9ee46a3496456fbec622c289d568cbf261616d40d3105780668a1405540"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "e16ccf5ff7421181c7504669b48313b096edcc70"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "9889ccb71ee822973b96e81b5159d624df7b7132ffa7d2197280cd7dbbb7a338"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SCS_GPU]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "1b3239d2ccb29b83156cd322f2bf72552d5a8a6e"
lazy = true
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "6ae4a8cb4eb2d0565b2b77a7dadce8f294d728525447515f7bdcf41bc113bb36"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.4+1/SCS_GPU.v3.2.4.x86_64-linux-gnu-cuda+12.4.tar.gz"
