[[SCS_GPU]]
arch = "x86_64"
git-tree-sha1 = "fd26118b4ba32448a8580d3e985f2e59fd4a0648"
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "77741127c3d74c73f7e38b84b71ca7d2ec15fef725de51a1fe0502eb0bf74a23"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v2.1.3+0/SCS_GPU.v2.1.3.x86_64-linux-gnu.tar.gz"
