[[SCS_GPU]]
arch = "x86_64"
git-tree-sha1 = "2aaf2d3c367d9e1a41ebf36b0bf47a08f363b09b"
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "c9a06452758cfea348325870de7309c8926e3df5ee779dc746c0f4ee915db5e6"
    url = "https://github.com/JuliaBinaryWrappers/SCS_GPU_jll.jl/releases/download/SCS_GPU-v3.2.3+1/SCS_GPU.v3.2.3.x86_64-linux-gnu.tar.gz"
