# Autogenerated wrapper script for SCS_GPU_jll for x86_64-linux-gnu
export libscsgpuindir

using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("SCS_GPU")
JLLWrappers.@declare_library_product(libscsgpuindir, "libscsgpuindir.so")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS_jll)
    JLLWrappers.@init_library_product(
        libscsgpuindir,
        "lib/libscsgpuindir.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
